version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: crypto_app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env.example
    depends_on:
      - timescaledb
      - postgres
      - redis
      - mlflow

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  postgres:
    image: postgres:14
    container_name: metadata_db
    environment:
      POSTGRES_USER: metadata_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d 

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mlflow:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.mlflow
    container_name: mlflow
    command: >
      mlflow server
      --backend-store-uri postgresql+psycopg2://metadata_user:password@postgres:5432/mlflow
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow/artifacts
    depends_on:
      - postgres

volumes:
  timescale_data:
  postgres_data:
  redis_data:
  mlflow_data:
